### ISSUE TITLE
How to use propono for one-to-many broadcast?

### ISSUE THREAD

**Issue by tardate** [meducation/propono#59]
I've just started looking at propono and so far love the ease of use.

The specific scenario I'd like to support is publishing message to multiple consumers (without the publisher needing to know if any/how many subscribers are listening).

Out of the box, this does not appear to work, because messages are dequeued as soon as read by one subscriber. i.e. only one of the many subscribers will ever get the message.

But maybe I'm overlooking some obvious configuration/usage guidelines to get 1-many to work.

I'd appreciate it if anyone can advise of this is possible (and if so how) before I get too lost on a yak-shaving expedition..

Cheers!

**Comment by tardate** [comment]
OK, stupid question. Think I've figured it out:

* when each subscriber shares the same application_name, they will operate as multiple workers attached to the same queue (i.e. one one will get to process each message)
* when subscribers to the same queue each have different a application_name, they will all receive their own copy of the message

Appreciate a steer if my understanding is off.

**Comment by radcliff** [comment]
@tardate :+1: i had the same question, searched, found this issue, and appreciated the simple explanation

**Comment by tardate** [comment]
@radcliff :beers:
